name: BedwarsXP
main: ldcr.BedwarsXP.BedwarsXP
version: 2.1.3
author: SakuraKooi
depend: [BedwarsRel]
commands:
  bedwarsxp:
    description: 经验起床
    usage: /bedwarsxp
    aliases: [bwxp]
  bedwarsxpedit:
    description: 修改玩家经验值
    usage: /bedwarsxpedit
    aliases: [editxp]
permissions:
  bedwarsxp.admin:
    description: 经验起床相关管理权限.
    default: op
